### ISSUE TITLE
support for go modules or vgo is missing

### ISSUE THREAD

**Issue by DrGo** [bradfitz/iter#10]
Thanks for the great package which I use every day (I do a lot of counting). Any plans to introduce support for go modules?  :)
Best

**Comment by dmitshur** [comment]
This package can be used in module mode without problems. Are you asking for a v1.0.0 release to made?

**Comment by bradfitz** [comment]
I added a go.mod file in https://github.com/bradfitz/iter/commit/e8f45d346db8021e0dd53899bf55eb6e21218b33 

Is that sufficient?

**Comment by DrGo** [comment]
yes. looking forward to version 2.0.0 :)
