### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by charlesvickery** [bradfitz/iter#3]
Hi Brad,

I'm writing a blog post and want to embed clickable code snippets (called [Sourceboxes](https://sourcegraph.com/blog/sourceboxes-a-better-way-to-embed-code-snippets)). Would you mind enabling this repo? It should only take 30 seconds.

https://sourcegraph.com/github.com/bradfitz/iter

Cheers,
Charles

**Comment by bradfitz** [comment]
That link doesn't give me anything to do, so maybe this was already done. Closing.
