### ISSUE TITLE
Typo in package documentation

### ISSUE THREAD

**Issue by jubobs** [bradfitz/iter#5]
Very minor, but

> Package iter provides a _syntantically_ different way to iterate over integers.

should read

> Package iter provides a _syntactically_ different way to iterate over integers.

(my emphasis)

**Comment by bradfitz** [comment]
Unfortunately this repo has a policy of maximum 1 commit in the history ever and no force pushes to rewrite history so I think we'll just have to let that typo live.

**Comment by Jubobs** [comment]
Fair enough, @bradfitz. I've closed the corresponding PR.

(Loved your interview from _Coders at Work_, by the way.)

**Comment by bradfitz** [comment]
> Fair enough, @bradfitz. I've closed the corresponding PR.

Not to ruin a joke by explaining it, but this whole repo/package was sort of an inside joke that I couldn't ever delete without breaking people. So now I perpetuate the joke by explaining that it was perfect at 1 commit and can't ever be changed.

> (Loved your interview from Coders at Work, by the way.)

Thanks! I, uh, kinda forget what I said. But I have a copy. Maybe I should read it. :)

**Comment by jubobs** [comment]
> [...] without breaking people.

If people are dumb enough to depend on such a small (yet useful!) package rather than copying `N` where needed, perhaps they should be punished... 😝
