### ISSUE TITLE
Under what license this package is distributed?

### ISSUE THREAD

**Issue by eclipseo** [bradfitz/iter#8]
Hi,

As this is a dependency of golang-github-anacrolix-missinggo, I am packaging golang-github-bradfitz-iter for my distribution. However no licensing information is available, which prevents me from continuing. Could you please add a License file?

**Comment by bradfitz** [comment]
Added a license, but I'm a little sad this joke is being packaged. Oh well. Sorry you have to do that.

**Comment by eclipseo** [comment]
Thanks! Yes it seems some people depended on a one liner after all!
